# app.toml: 应用主配置文件
 
# 应用名称，代码里可通过 env.AppName() 方法读取到
APPName = "pywebio-file-appui"
 
# 运行模式，可配置值：
# debug	: 调试，	对应常量 env.RunModeDebug
# test	 : 测试，	对应常量 env.RunModeTest
# release  : 线上发布， 对应常量 env.RunModeRelease
# 程序代码可以通过 env.RunMode() 获取该值
RunMode = "debug"
 
# HTTPServer 的配置
[HTTPServer]
 
# http server 监听的端口
# 配置的 {env.LISTEN_PORT|8080} 的含义：
# 先尝试从系统的环境变量里读取key=LISTEN_PORT的环境变量值，若不存在或者为空，使用默认值8081
# 0.0.0.0表示监听本机所有ip地址，可以使用localhost访问
Listen="0.0.0.0:{env.LISTEN_PORT|8081}"

# 读超时时间，ms，可选配置
ReadTimeout=5000 # 1s
 
# 写超时时间（从请求读取完开始计算），ms，可选配置
# 若要使用debug功能，请设置一个很大的值
WriteTimeout=10000 # 4s

# 空闲等待超时时间, ms, 可选配置
# 当设置keep-alives开启时(HTTP Server默认开启), 同一个tcp连接, 读取下一个请求的等待时间
# 若client 出现 connection reset by peer, 可能和此参数有关
# 请根据实际情况进行调整
IdleTimeout=5000 # 1s
